spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/kotlin-study.h2;AUTO_SERVER=true
    username: sa
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  flyway:
    url: jdbc:h2:file:~/kotlin-study.h2;AUTO_SERVER=true
    user: sa
    enabled: true
logging:
  file:
    path: .
    name: kotlin-study.log
    max-size: 20MB
